// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOHH-5xpD2AaKsjOQFb6KpfGaBukgDsYQ',
    appId: '1:330440029500:web:1d379b157dc17e0a769a39',
    messagingSenderId: '330440029500',
    projectId: 'sitiosturisticos-d68a6',
    authDomain: 'sitiosturisticos-d68a6.firebaseapp.com',
    storageBucket: 'sitiosturisticos-d68a6.appspot.com',
    measurementId: 'G-2S4N8YCYRN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwTHSIdxpZLpJTv_2grcHvkIFP6A6bzOY',
    appId: '1:330440029500:android:96ba30e69d7561b6769a39',
    messagingSenderId: '330440029500',
    projectId: 'sitiosturisticos-d68a6',
    storageBucket: 'sitiosturisticos-d68a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRfdSToDqMGqqHDIz7eUuolvtR8Plngpg',
    appId: '1:330440029500:ios:a0a4f5e1b18eb7bc769a39',
    messagingSenderId: '330440029500',
    projectId: 'sitiosturisticos-d68a6',
    storageBucket: 'sitiosturisticos-d68a6.appspot.com',
    iosBundleId: 'com.example.flutterSitiosTuristicos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRfdSToDqMGqqHDIz7eUuolvtR8Plngpg',
    appId: '1:330440029500:ios:631b380f2075b2a4769a39',
    messagingSenderId: '330440029500',
    projectId: 'sitiosturisticos-d68a6',
    storageBucket: 'sitiosturisticos-d68a6.appspot.com',
    iosBundleId: 'com.example.flutterSitiosTuristicos.RunnerTests',
  );
}
